### ISSUE TITLE
docker/.env file missing

### ISSUE THREAD

**Issue by Call-Me-G-Now** [MnAppsNet/firefly-pico-dockerfile#1]
Can't build with the current Dockerfile:
https://github.com/MnAppsNet/firefly-pico-dockerfile/blob/1287510b14aca1627d020c48dc6e823417e5e18f/Dockerfile#L53
docker/.env doesn't exist. I guess you forgot to add it to your repo? or is this the `back/.env.example` from the cioraneanu/firefly-pico#10 repo?

**Comment by emkalyvas** [comment]
Oh you are right, I had it in the gitignore by accident :)
